### PR TITLE
Integrate debug logs on controller actions + discord webhook integration

### PR DESCRIPTION
**Pull request by kusaljayawardhana**

### CODE REVIEW

**Comment by NuwanJ** [comment]
@kusaljayawardhana I can see you have put a good effort in adding the logs for every control action. 

But, since we are using a file-based logging system (file read/write needs a lot of CPU time and storage), it is better to record only the try catch-related errors. (add try-catch blocks to the controllers that don't contain them) 

Additionally, while you are implementing new features, can use debug logs for your own inspections and clean them before submitting a Pull Request.

**Comment by NuwanJ** [comment]
Additional comment for your knowledge: To track the usage and trigger of specific events, we can integrate services like Google Analytics and Google Tag Manager, and they already have support to map the data into various diagrams and dashboards and analyze data.

**Comment by kusaljayawardhana** [comment]
> i

I will make the changes

**Comment by kusaljayawardhana** [comment]
> Additional comment for your knowledge: To track the usage and trigger of specific events, we can integrate services like Google Analytics and Google Tag Manager, and they already have support to map the data into various diagrams and dashboards and analyze data.

Thank you and i will look more into this.

**Review by NuwanJ — APPROVED** [review]

**Pull request merged**
